#!/data/data/com.termux/files/usr/bin/bash
# ============================================================================
#  Oksskolten Termux Reader — Native Android (NDK) Installer
#  The "Unstoppable" Loader Bypass (Surgical Edition)
# ============================================================================
set -euo pipefail  # Exit on error, unset vars, and pipe failures

R='\033[0;31m'; G='\033[0;32m'; Y='\033[1;33m'; C='\033[0;36m'; B='\033[1;34m'; NC='\033[0m'
DIM='\033[0;2m'

banner() {
    clear
    echo -e "${B}╔═══════════════════════════════════════════╗${NC}"
    echo -e "${B}║    ${G}📖  Oksskolten Termux Reader  📖${NC}    ${B}║${NC}"
    echo -e "${B}║       Native Android · Zero Overhead      ║${NC}"
    echo -e "${B}╚═══════════════════════════════════════════╝${NC}"
}

step() { echo -e "\n${B}[▸]${NC} $1"; }
ok()   { echo -e "  ${G}[✓]${NC} $1"; }
warn() { echo -e "  ${Y}[!]${NC} $1"; }
err()  { echo -e "  ${R}[✗]${NC} $1"; exit 1; }

banner

# --- 1. Environment ---
step "Ensuring native environment..."
pkg update -y
pkg install -y nodejs-lts git curl python make clang binutils pkg-config libsqlite openssl rust termux-elf-cleaner
ok "Toolchain ready"

# --- 2. Source Management ---
INSTALL_DIR="$HOME/oksskolten"
step "Fetching source..."
if [ -d "$INSTALL_DIR/.git" ]; then
    cd "$INSTALL_DIR" && git pull --ff-only
else
    git clone https://github.com/muxd22-alt/termux_reader.git "$INSTALL_DIR"
    cd "$INSTALL_DIR"
fi

# --- 3. Platform Forcing ---
step "Patching configs..."
# Patch package files to allow 'android' as an OS
find . -maxdepth 2 -name "package*.json" -exec sed -i 's/"os": \[/"os": \["android", /g' {} +
# Wipe engine restrictions
sed -i '/"engines": {/,/}/d' package.json 2>/dev/null || true
ok "Manifests patched"

# --- 4. Native Build ---
step "Building native modules (LibSQL/SQLite)..."
# Setting flags to ensure we use Termux's libraries
export LDFLAGS="-L$PREFIX/lib"
export CPPFLAGS="-I$PREFIX/include"
# Force local compilation
npm install --no-fund --no-audit --build-from-source || {
    warn "Direct build failed, attempting ignore-scripts fallback..."
    npm install --no-fund --no-audit --ignore-scripts
}

# --- 5. The "Unstoppable" Bypass ---
step "Applying Surgical Native Bypass..."

# Identify Architecture
ARCH=$(uname -m)
[ "$ARCH" == "aarch64" ] && LIB_ARCH="arm64" || LIB_ARCH="arm"

# 5a. Find and clean ALL .node files
find node_modules -name "*.node" | while read -r NODE_FILE; do
    echo -e "  ${DIM}Cleaning ELF headers: $(basename "$NODE_FILE")${NC}"
    termux-elf-cleaner "$NODE_FILE" > /dev/null 2>&1 || true
done

# 5b. Overwrite LibSQL Loaders
# This target index.js files inside @libsql and replaces them with a hard-coded redirect
FOUND_LIBS=0
find node_modules/@libsql -name "index.js" 2>/dev/null | while read -r LIBJS; do
    DIR=$(dirname "$LIBJS")
    # Check if there is a .node file in this directory or nearby
    NODE_FILE=$(find "$DIR" -name "*.node" | head -1)
    
    if [ -n "$NODE_FILE" ]; then
        REL_NODE=$(basename "$NODE_FILE")
        echo -e "  ${C}Surgically overriding: $LIBJS${NC}"
        cat > "$LIBJS" << JSBOOT
/** Termux Native Bypass - Generated by Installer **/
try {
  module.exports = require("./$REL_NODE");
} catch (e) {
  try {
    module.exports = require("../$REL_NODE");
  } catch (err) {
    console.error("\n[Termux Error] Could not load native binding: $REL_NODE");
    console.error("Path attempted: " + __dirname);
    process.exit(1);
  }
}
JSBOOT
        FOUND_LIBS=1
    fi
done

# 5c. Emergency Symlink Fallback
if [ "$FOUND_LIBS" -eq 0 ]; then
    warn "Primary bypass failed. Attempting symlink redirect..."
    mkdir -p "node_modules/@libsql"
    # Link whatever was built (linux-arm64-gnu) to the name Node/Android expects
    COMPANION=$(find node_modules/@libsql -name "linux-*" -type d | head -1 || echo "")
    if [ -n "$COMPANION" ]; then
        ln -sf "$(basename "$COMPANION")" "node_modules/@libsql/android-$LIB_ARCH"
        ok "Symlinked $(basename "$COMPANION") -> android-$LIB_ARCH"
    fi
fi

# 5d. Runtime Intercept (The "Safety Net")
if [ -f "server/index.ts" ]; then
    if ! grep -q "Module.prototype.require" "server/index.ts"; then
        # Safer injection: uses a temporary file to ensure we don't mangle the code
        echo 'import Module from "node:module";
// @ts-ignore
const origRequire = Module.prototype.require;
// @ts-ignore
Module.prototype.require = function(id) {
  if (id.includes("android")) return origRequire.call(this, id.replace("android", "linux"));
  return origRequire.apply(this, arguments);
};' > inject.tmp
        cat server/index.ts >> inject.tmp
        mv inject.tmp server/index.ts
    fi
fi
ok "Bypass stack applied"

# --- 6. Build Frontend ---
step "Building frontend..."
npm run build 2>&1 | tail -n 5 || warn "Frontend build failed/skipped."

# --- 7. Final Reader Command ---
mkdir -p "$PREFIX/bin"
cat > "$PREFIX/bin/reader" << 'READEREOF'
#!/data/data/com.termux/files/usr/bin/bash
R='\033[0;31m'; G='\033[0;32m'; Y='\033[1;33m'; B='\033[1;34m'; W='\033[1;37m'; NC='\033[0m'
APP_DIR="$HOME/oksskolten"
PORT="${READER_PORT:-3000}"

# Improved IP detection (handles WiFi, cellular, and tethering)
LOCAL_IP=$(ip -4 addr show 2>/dev/null | grep -oP '(?<=inet\s)[\d.]+' | grep -v '127\.0\.0\.1' | head -1 || echo "127.0.0.1")

clear
echo -e "  ${W}╔═══════════════════════════════════════════════════╗${NC}"
echo -e "  ${W}║   ${G}📖 Oksskolten RSS Reader${NC}                        ${W}║${NC}"
echo -e "  ${W}╠═══════════════════════════════════════════════════╣${NC}"
echo -e "  ${W}║   ${B}Access:${NC}     http://${LOCAL_IP}:${PORT}"
echo -e "  ${W}║   ${Y}Logs:${NC}       ${APP_DIR}/data/reader.log"
echo -e "  ${W}╚═══════════════════════════════════════════════════╝${NC}\n"

cd "$APP_DIR"
export PORT="$PORT"
export DATA_DIR="${DATA_DIR:-$APP_DIR/data}"
mkdir -p "$DATA_DIR"

if [ -d "$APP_DIR/dist" ]; then
    export NODE_ENV=production
else
    export NODE_ENV=development
    export AUTH_DISABLED=1
fi

# --dns-result-order is critical for Termux to avoid IPv6 hang-ups
exec npx tsx --dns-result-order=ipv4first server/index.ts
READEREOF
chmod +x "$PREFIX/bin/reader"

echo -e "\n${G}✅ Setup Complete!${NC}"
echo -e "Start the reader with: ${C}reader${NC}\n"